<?xml version="1.0" encoding="UTF-8"?>
<test_result>
  <test_runs>
        <test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246816" external_run_id="A1"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="9" status="Passed" started="1602748246816" external_run_id="A2"/>
        <test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="9" status="Passed" started="1602748246816" external_run_id="A3"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="Nico" duration="5" status="Passed" started="1602748246816" external_run_id="N2"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="Nico" duration="10" status="Skipped" started="1602748246816" external_run_id="N1"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Failed" started="1602748246816" external_run_id="B2">
	        <error type="java.lang.AssertionError" message="expected:'111' but was:'222'">java.lang.AssertionError: expected:'111' but was:'222'
			at org.junit.Assert.fail(Assert.java:88)
			at org.junit.Assert.failNotEquals(Assert.java:743)
			at org.junit.Assert.assertEquals(Assert.java:118)
	       </error>
	  </test_run>
  </test_runs>
</test_result>
